name = "se-tool-matrix"
compatibility_date = "2025-07-06"
pages_build_output_dir = "."

[env.production]
name = "se-tool-matrix"

[env.production.ai]
binding = "AI"

[env.preview]
name = "se-tool-matrix-preview"

[env.preview.ai]
binding = "AI"
